[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_VERSION = "20.11.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20.11.1" }
